export enum ReserveReleaseReason {
  SALE_RESERVATION = 'SALE_RESERVATION',
  SALE_CANCELLATION = 'SALE_CANCELLATION',
  DELIVERY_RESERVATION = 'DELIVERY_RESERVATION',
  DELIVERY_CANCELLATION = 'DELIVERY_CANCELLATION',
  DELIVERY_RETURN = 'DELIVERY_RETURN',
}
